const express = require("express");
const router = express.Router();
const auth = require("./auth");
const user = require("./user");
const post = require("./post");
const voucher = require("./voucher");
const category = require("./categorys");
const payment = require("./payment");
router.use("/auth", auth);
router.use("/user", user);
router.use("/post", post);
router.use("/voucher", voucher);
router.use("/category", category);
router.use("/payment", payment);
module.exports = router;
